/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.smartcity.SCREENS;

/**
 *
 * @author Admin
 */
public class CustomerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public CustomerDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        birth = new javax.swing.JButton();
        death = new javax.swing.JButton();
        complaints = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        jLabel1.setText("CUSTOMER DASHBOARD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 30, 275, 38);

        birth.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        birth.setText("ADD BIRTH CERTIFICATE");
        birth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthActionPerformed(evt);
            }
        });
        getContentPane().add(birth);
        birth.setBounds(80, 110, 240, 33);

        death.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        death.setText("ADD DEATH CERTIFICATE");
        death.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deathActionPerformed(evt);
            }
        });
        getContentPane().add(death);
        death.setBounds(80, 180, 240, 34);

        complaints.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        complaints.setText("ADD COMPLAIINTS");
        complaints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complaintsActionPerformed(evt);
            }
        });
        getContentPane().add(complaints);
        complaints.setBounds(80, 240, 240, 38);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void complaintsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complaintsActionPerformed
        // TODO add your handling code here:
        
       AddComplaint sc = new AddComplaint();
        sc.setVisible(true);
    }//GEN-LAST:event_complaintsActionPerformed

    private void birthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthActionPerformed
        // TODO add your handling code here:
      AddBirth user = new AddBirth();
        user.setVisible(true);
        
        
    }//GEN-LAST:event_birthActionPerformed

    private void deathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deathActionPerformed
        // TODO add your handling code here:
       AddDeath sc = new  AddDeath();
        sc.setVisible(true);
        
    }//GEN-LAST:event_deathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton birth;
    private javax.swing.JButton complaints;
    private javax.swing.JButton death;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
